Remove duplicate project page entries (workspace, recent changes, test result)
jenkinsci/maven-plugin pull request #281
Opened 2022-07-25 08:55 UTC by NotMyFault

The change proposed deduplicates entries on the project page. The maven plugin depends on the JUnit plugin to be installed, which already adds a link to the test results, the current implementation adds another one:
![a](https://user-images.githubusercontent.com/13383509/180738264-f1e28dcf-ffd7-407b-ad4f-ee8523967069.png)

2022-07-25 08:55 UTC, NotMyFault commented
/label bug

2022-07-25 08:59 UTC, NotMyFault commented
/label bug

2022-07-25 09:23 UTC, timja commented
/label bug

2022-07-25 09:24 UTC, timja commented
/label bug

2022-07-25 09:32 UTC, NotMyFault commented
/label bug

2022-07-25 10:19 UTC, NotMyFault commented
cc @olamy and apologizes for the comment spam :P

2022-07-26 00:49 UTC, olamy commented
> cc @olamy and apologizes for the comment spam :P

/label no problem 🤣

2022-07-26 06:16 UTC, olamy requested changes

2022-07-26 06:16 UTC, olamy commented on src/main/resources/hudson/maven/MavenModuleSet/index.jelly
> -        <t:summary icon="folder.svg" href="ws/" permission="${it.WORKSPACE}">
why removing access to workspace? this has nothing to do with duplicate link test

2022-07-26 06:16 UTC, olamy commented on src/main/resources/hudson/maven/MavenModuleSet/index.jelly
> -        <t:summary icon="notepad.svg" href="changes">
why removing access to changes? this has nothing to do with duplicate link test

2022-07-26 06:17 UTC, olamy commented
@NotMyFault it looks you're removing too much here :)

2022-07-26 07:41 UTC, NotMyFault commented
> @NotMyFault it looks you're removing too much here :)

Oh, I forgot to mention that I applied https://github.com/jenkinsci/jenkins/pull/6918 while at it.
Core removed those from the main page in favor of the sidepanel.

2022-07-26 10:22 UTC, olamy commented
> > @NotMyFault it looks you're removing too much here :)
> 
> Oh, I forgot to mention that I applied [jenkinsci/jenkins#6918](https://github.com/jenkinsci/jenkins/pull/6918) while at it. Core removed those from the main page in favor of the sidepanel.

no worries. I have updated the PR title.
thanks

2022-07-26 10:22 UTC, merged